// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(RentACarContext))]
    [Migration("20220918144027_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "akif@ozdemir.com",
                            FirstName = "Mehmet Akif",
                            LastName = "Özdemir",
                            PasswordHash = new byte[] { 75, 34, 111, 142, 165, 216, 176, 25, 36, 179, 248, 168, 148, 94, 246, 151, 185, 148, 40, 37, 34, 87, 58, 7, 120, 73, 47, 151, 145, 33, 205, 36, 118, 48, 199, 52, 222, 191, 226, 93, 162, 111, 248, 34, 166, 51, 113, 52, 168, 161, 89, 28, 150, 162, 83, 63, 41, 46, 149, 2, 246, 0, 148, 214 },
                            PasswordSalt = new byte[] { 21, 122, 172, 11, 118, 182, 139, 245, 29, 227, 10, 85, 93, 3, 217, 228, 33, 121, 144, 228, 13, 31, 179, 44, 139, 239, 247, 162, 86, 80, 139, 83, 153, 83, 108, 70, 65, 76, 193, 142, 252, 72, 142, 186, 224, 107, 96, 159, 18, 58, 40, 59, 37, 98, 130, 7, 61, 199, 253, 155, 241, 204, 20, 154, 126, 25, 127, 197, 96, 71, 27, 68, 120, 57, 114, 188, 254, 186, 230, 39, 100, 25, 134, 1, 138, 160, 219, 158, 146, 34, 143, 80, 16, 242, 189, 3, 214, 20, 132, 183, 208, 65, 196, 189, 85, 114, 240, 168, 11, 34, 36, 143, 180, 14, 201, 91, 195, 215, 132, 29, 107, 203, 128, 159, 27, 58, 224, 99 },
                            Status = true
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserOperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperationClaimId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "BMW"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Skoda"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Renault"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Volkswagen"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("DailyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            BrandId = 2,
                            ColorId = 3,
                            DailyPrice = 400,
                            Description = "Fabia",
                            ModelYear = 2018
                        },
                        new
                        {
                            CarId = 2,
                            BrandId = 4,
                            ColorId = 4,
                            DailyPrice = 500,
                            Description = "Tiguan",
                            ModelYear = 2020
                        },
                        new
                        {
                            CarId = 3,
                            BrandId = 3,
                            ColorId = 1,
                            DailyPrice = 300,
                            Description = "Fluence",
                            ModelYear = 2018
                        },
                        new
                        {
                            CarId = 4,
                            BrandId = 4,
                            ColorId = 5,
                            DailyPrice = 400,
                            Description = "Golf",
                            ModelYear = 2010
                        },
                        new
                        {
                            CarId = 5,
                            BrandId = 1,
                            ColorId = 2,
                            DailyPrice = 800,
                            Description = "X7",
                            ModelYear = 2018
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Date = new DateTime(2022, 9, 18, 17, 40, 27, 348, DateTimeKind.Local).AddTicks(9940),
                            ImagePath = "3cffc9b7-e111-4f2e-98bb-70f38a325232.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Date = new DateTime(2022, 9, 18, 17, 40, 27, 348, DateTimeKind.Local).AddTicks(9950),
                            ImagePath = "2e73e3d1-4add-4b63-8e2d-5fec0188ef5d.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Date = new DateTime(2022, 9, 18, 17, 40, 27, 348, DateTimeKind.Local).AddTicks(9951),
                            ImagePath = "35676709-24bd-4b90-90df-d737bf8d1159.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            Date = new DateTime(2022, 9, 18, 17, 40, 27, 348, DateTimeKind.Local).AddTicks(9952),
                            ImagePath = "d6448427-0c49-4219-a8bf-625726cd1ad8.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            Date = new DateTime(2022, 9, 18, 17, 40, 27, 348, DateTimeKind.Local).AddTicks(9953),
                            ImagePath = "c694f801-94c7-4217-9bde-f219e91825e7.jpg"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"), 1L, 1);

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorName = "White"
                        },
                        new
                        {
                            ColorId = 2,
                            ColorName = "Black"
                        },
                        new
                        {
                            ColorId = 3,
                            ColorName = "Orange"
                        },
                        new
                        {
                            ColorId = 4,
                            ColorName = "Red"
                        },
                        new
                        {
                            ColorId = 5,
                            ColorName = "Grey"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Entitites.Concrete.Car", b =>
                {
                    b.HasOne("Entitites.Concrete.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitites.Concrete.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entitites.Concrete.CarImage", b =>
                {
                    b.HasOne("Entitites.Concrete.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entitites.Concrete.Rental", b =>
                {
                    b.HasOne("Entitites.Concrete.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
