// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(RentACarContext))]
    [Migration("20220921144409_mig2")]
    partial class mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "akif@ozdemir.com",
                            FirstName = "Mehmet Akif",
                            LastName = "Özdemir",
                            PasswordHash = new byte[] { 226, 14, 87, 198, 179, 73, 167, 110, 207, 34, 79, 34, 214, 48, 103, 10, 210, 187, 89, 36, 149, 133, 241, 67, 66, 241, 194, 205, 60, 235, 120, 160, 13, 152, 185, 89, 210, 16, 60, 176, 83, 117, 174, 116, 33, 99, 12, 162, 51, 170, 86, 114, 229, 141, 172, 35, 193, 204, 136, 115, 16, 46, 231, 227 },
                            PasswordSalt = new byte[] { 47, 184, 225, 167, 97, 248, 86, 204, 63, 59, 111, 239, 109, 131, 130, 65, 41, 122, 167, 37, 216, 249, 245, 46, 65, 137, 100, 36, 234, 164, 103, 86, 190, 22, 149, 246, 150, 16, 188, 27, 86, 226, 93, 59, 1, 7, 3, 248, 109, 9, 85, 238, 10, 67, 170, 107, 68, 189, 128, 186, 253, 3, 147, 45, 233, 215, 250, 242, 218, 47, 60, 192, 81, 175, 141, 251, 196, 57, 156, 135, 211, 190, 217, 77, 119, 80, 90, 8, 111, 189, 57, 192, 115, 169, 92, 86, 4, 210, 67, 13, 115, 195, 18, 175, 3, 99, 195, 119, 111, 41, 148, 20, 214, 52, 3, 58, 202, 162, 56, 238, 9, 61, 23, 124, 179, 103, 181, 153 },
                            Status = true
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserOperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperationClaimId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "BMW"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Skoda"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Renault"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Volkswagen"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("DailyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRentable")
                        .HasColumnType("bit");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            BrandId = 2,
                            ColorId = 3,
                            DailyPrice = 400,
                            Description = "Fabia",
                            IsRentable = false,
                            ModelYear = 2018,
                            OwnerId = 0
                        },
                        new
                        {
                            CarId = 2,
                            BrandId = 4,
                            ColorId = 4,
                            DailyPrice = 500,
                            Description = "Tiguan",
                            IsRentable = false,
                            ModelYear = 2020,
                            OwnerId = 0
                        },
                        new
                        {
                            CarId = 3,
                            BrandId = 3,
                            ColorId = 1,
                            DailyPrice = 300,
                            Description = "Fluence",
                            IsRentable = false,
                            ModelYear = 2018,
                            OwnerId = 0
                        },
                        new
                        {
                            CarId = 4,
                            BrandId = 4,
                            ColorId = 5,
                            DailyPrice = 400,
                            Description = "Golf",
                            IsRentable = false,
                            ModelYear = 2010,
                            OwnerId = 0
                        },
                        new
                        {
                            CarId = 5,
                            BrandId = 1,
                            ColorId = 2,
                            DailyPrice = 800,
                            Description = "X7",
                            IsRentable = false,
                            ModelYear = 2018,
                            OwnerId = 0
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Date = new DateTime(2022, 9, 21, 17, 44, 9, 216, DateTimeKind.Local).AddTicks(2929),
                            ImagePath = "3cffc9b7-e111-4f2e-98bb-70f38a325232.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Date = new DateTime(2022, 9, 21, 17, 44, 9, 216, DateTimeKind.Local).AddTicks(2939),
                            ImagePath = "2e73e3d1-4add-4b63-8e2d-5fec0188ef5d.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Date = new DateTime(2022, 9, 21, 17, 44, 9, 216, DateTimeKind.Local).AddTicks(2940),
                            ImagePath = "35676709-24bd-4b90-90df-d737bf8d1159.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            Date = new DateTime(2022, 9, 21, 17, 44, 9, 216, DateTimeKind.Local).AddTicks(2940),
                            ImagePath = "d6448427-0c49-4219-a8bf-625726cd1ad8.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            Date = new DateTime(2022, 9, 21, 17, 44, 9, 216, DateTimeKind.Local).AddTicks(2941),
                            ImagePath = "c694f801-94c7-4217-9bde-f219e91825e7.jpg"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"), 1L, 1);

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorName = "White"
                        },
                        new
                        {
                            ColorId = 2,
                            ColorName = "Black"
                        },
                        new
                        {
                            ColorId = 3,
                            ColorName = "Orange"
                        },
                        new
                        {
                            ColorId = 4,
                            ColorName = "Red"
                        },
                        new
                        {
                            ColorId = 5,
                            ColorName = "Grey"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Entitites.Concrete.Car", b =>
                {
                    b.HasOne("Entitites.Concrete.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitites.Concrete.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entitites.Concrete.CarImage", b =>
                {
                    b.HasOne("Entitites.Concrete.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entitites.Concrete.Rental", b =>
                {
                    b.HasOne("Entitites.Concrete.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
