// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(RentACarContext))]
    [Migration("20220921144507_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "akif@ozdemir.com",
                            FirstName = "Mehmet Akif",
                            LastName = "Özdemir",
                            PasswordHash = new byte[] { 48, 200, 91, 229, 131, 36, 121, 101, 182, 121, 71, 223, 239, 158, 79, 4, 212, 61, 9, 131, 252, 131, 226, 2, 246, 90, 167, 161, 65, 156, 7, 63, 195, 217, 130, 3, 61, 36, 151, 175, 0, 154, 52, 126, 240, 151, 104, 85, 93, 85, 23, 112, 58, 72, 200, 16, 130, 155, 61, 157, 48, 89, 111, 148 },
                            PasswordSalt = new byte[] { 194, 114, 170, 22, 61, 234, 38, 114, 179, 13, 149, 14, 127, 157, 86, 82, 153, 215, 48, 143, 173, 211, 56, 162, 173, 101, 190, 8, 207, 131, 255, 208, 208, 71, 174, 22, 213, 30, 124, 102, 170, 125, 249, 56, 221, 28, 89, 108, 177, 149, 67, 112, 221, 184, 65, 226, 148, 159, 47, 84, 121, 48, 222, 11, 235, 7, 128, 152, 139, 235, 163, 240, 150, 188, 223, 117, 191, 186, 37, 202, 63, 79, 92, 33, 12, 155, 35, 157, 247, 154, 163, 93, 72, 182, 229, 182, 179, 11, 176, 87, 88, 103, 172, 222, 254, 224, 51, 193, 112, 235, 26, 234, 107, 32, 206, 90, 203, 247, 99, 41, 4, 147, 90, 60, 25, 85, 60, 158 },
                            Status = true
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserOperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OperationClaimId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserOperationClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OperationClaimId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "BMW"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Skoda"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Renault"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Volkswagen"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("DailyPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRentable")
                        .HasColumnType("bit");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            BrandId = 2,
                            ColorId = 3,
                            DailyPrice = 400,
                            Description = "Fabia",
                            IsRentable = true,
                            ModelYear = 2018,
                            OwnerId = 1
                        },
                        new
                        {
                            CarId = 2,
                            BrandId = 4,
                            ColorId = 4,
                            DailyPrice = 500,
                            Description = "Tiguan",
                            IsRentable = true,
                            ModelYear = 2020,
                            OwnerId = 1
                        },
                        new
                        {
                            CarId = 3,
                            BrandId = 3,
                            ColorId = 1,
                            DailyPrice = 300,
                            Description = "Fluence",
                            IsRentable = true,
                            ModelYear = 2018,
                            OwnerId = 1
                        },
                        new
                        {
                            CarId = 4,
                            BrandId = 4,
                            ColorId = 5,
                            DailyPrice = 400,
                            Description = "Golf",
                            IsRentable = true,
                            ModelYear = 2010,
                            OwnerId = 1
                        },
                        new
                        {
                            CarId = 5,
                            BrandId = 1,
                            ColorId = 2,
                            DailyPrice = 800,
                            Description = "X7",
                            IsRentable = true,
                            ModelYear = 2018,
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            Date = new DateTime(2022, 9, 21, 17, 45, 7, 454, DateTimeKind.Local).AddTicks(4441),
                            ImagePath = "3cffc9b7-e111-4f2e-98bb-70f38a325232.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            Date = new DateTime(2022, 9, 21, 17, 45, 7, 454, DateTimeKind.Local).AddTicks(4450),
                            ImagePath = "2e73e3d1-4add-4b63-8e2d-5fec0188ef5d.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            Date = new DateTime(2022, 9, 21, 17, 45, 7, 454, DateTimeKind.Local).AddTicks(4451),
                            ImagePath = "35676709-24bd-4b90-90df-d737bf8d1159.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            Date = new DateTime(2022, 9, 21, 17, 45, 7, 454, DateTimeKind.Local).AddTicks(4452),
                            ImagePath = "d6448427-0c49-4219-a8bf-625726cd1ad8.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            Date = new DateTime(2022, 9, 21, 17, 45, 7, 454, DateTimeKind.Local).AddTicks(4452),
                            ImagePath = "c694f801-94c7-4217-9bde-f219e91825e7.jpg"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"), 1L, 1);

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorName = "White"
                        },
                        new
                        {
                            ColorId = 2,
                            ColorName = "Black"
                        },
                        new
                        {
                            ColorId = 3,
                            ColorName = "Orange"
                        },
                        new
                        {
                            ColorId = 4,
                            ColorName = "Red"
                        },
                        new
                        {
                            ColorId = 5,
                            ColorName = "Grey"
                        });
                });

            modelBuilder.Entity("Entitites.Concrete.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Entitites.Concrete.Car", b =>
                {
                    b.HasOne("Entitites.Concrete.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitites.Concrete.Color", null)
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entitites.Concrete.CarImage", b =>
                {
                    b.HasOne("Entitites.Concrete.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entitites.Concrete.Rental", b =>
                {
                    b.HasOne("Entitites.Concrete.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
